#pragma once

// PUBG MOBILE 2.5.0 SDK generated by Huy#3877 

namespace SDK
{
//---------------------------------------------------------------------------
//Classes
//---------------------------------------------------------------------------

// BlueprintGeneratedClass BP_Rifle_M416_BattleItemHandle.BP_Rifle_M416_BattleItemHandle_C
// 0x0000 (0x0691 - 0x0691)
class UBP_Rifle_M416_BattleItemHandle_C : public UBattleItemHandle_MainWeapon_C
{
public:

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("BlueprintGeneratedClass BP_Rifle_M416_BattleItemHandle.BP_Rifle_M416_BattleItemHandle_C");
		return pStaticClass;
	}

};


}

