#pragma once

// PUBG MOBILE 2.5.0 SDK generated by Huy#3877 

#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function BP_Phone_Anim.BP_Phone_Anim_C.AnimNotify_ShowPhone
struct UBP_Phone_Anim_C_AnimNotify_ShowPhone_Params
{
};

// Function BP_Phone_Anim.BP_Phone_Anim_C.ExecuteUbergraph_BP_Phone_Anim
struct UBP_Phone_Anim_C_ExecuteUbergraph_BP_Phone_Anim_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

