#pragma once

// PUBG MOBILE 2.5.0 SDK generated by Huy#3877 

namespace SDK
{
//---------------------------------------------------------------------------
//Classes
//---------------------------------------------------------------------------

// BlueprintGeneratedClass BattleItemHandle_Jacket_633_int.BattleItemHandle_Jacket_633_int_C
// 0x0000 (0x09EA - 0x09EA)
class UBattleItemHandle_Jacket_633_int_C : public UBattleItemHandle_AvatarBP_C
{
public:

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("BlueprintGeneratedClass BattleItemHandle_Jacket_633_int.BattleItemHandle_Jacket_633_int_C");
		return pStaticClass;
	}

};


}

