#pragma once

// PUBG MOBILE 2.5.0 SDK generated by Huy#3877 

namespace SDK
{
//---------------------------------------------------------------------------
//Classes
//---------------------------------------------------------------------------

// BlueprintGeneratedClass BattleItemHandle_GlideBP.BattleItemHandle_GlideBP_C
// 0x000A (0x09F4 - 0x09EA)
class UBattleItemHandle_GlideBP_C : public UBattleItemHandle_AvatarBP_C
{
public:
	unsigned char                                      UnknownData00[0x2];                                       // 0x09EA(0x0002) MISSED OFFSET
	class UAnimMontage*                                startAimn;                                                // 0x09EC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	class UAnimSequenceBase*                           IdleAnim;                                                 // 0x09F0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("BlueprintGeneratedClass BattleItemHandle_GlideBP.BattleItemHandle_GlideBP_C");
		return pStaticClass;
	}


	void NewFunction_1();
};


}

