#pragma once

// PUBG MOBILE 2.5.0 SDK generated by Huy#3877 

namespace SDK
{
//---------------------------------------------------------------------------
//Classes
//---------------------------------------------------------------------------

// Class AI.AESpawner
// 0x0028 (0x0410 - 0x03E8)
class AAESpawner : public ASTSpawnerBase
{
public:
	TArray<class UClass*>                              TeamAIClasses;                                            // 0x03E8(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                SpawnerCampItemID;                                        // 0x03F4(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                SpawnerTeamID;                                            // 0x03F8(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	TEnumAsByte<EBotCategray>                          SpeciesCategory;                                          // 0x03FC(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x3];                                       // 0x03FD(0x0003) MISSED OFFSET
	TArray<class UActorComponent*>                     TeamAIComponents;                                         // 0x0400(0x000C) (ExportObject, ZeroConstructor)
	unsigned char                                      UnknownData01[0x4];                                       // 0x040C(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.AESpawner");
		return pStaticClass;
	}


	void SwitchTeamAI(bool bEnable);
	void OnUnitSpawned(uint32_t InSpawnerID, class APawn* AIPawn, int ConfigId);
	void OnSpawnTimingRipe(bool IsRipe);
	void OnOwnedMobDead(class ASTExtraSimpleCharacter* DeadCharacter, class AController* Killer, class AActor* DamageCauser, const struct FHitResult& KillingHitInfo, const struct FVector& KillingHitImpulseDir, class UClass* KillingHitDamageType);
	void OnOwnedFakePlayerDead(class ASTExtraBaseCharacter* DeadCharacter, class AController* Killer, class AActor* DamageCauser, const struct FHitResult& KillingHitInfo, const struct FVector& KillingHitImpulseDir, class UClass* KillingHitDamageType);
	TEnumAsByte<EBotCategray> GetSpeciesCategory();
	float GetSpawnerTeamID();
	int GenerateParamID(int ConfigId, int BaseParamID);
	void DeactivateSpawner();
	void BPOnUnitSpawned(class APawn* AIPawn, int ConfigId);
	void ActivateSpawner();
};


// Class AI.AESpawnSubsystem
// 0x0060 (0x0140 - 0x00E0)
class UAESpawnSubsystem : public USTSpawnSubsystem
{
public:
	unsigned char                                      UnknownData00[0x4C];                                      // 0x00E0(0x004C) MISSED OFFSET
	struct FFakePlayerParams                           CacheFPParams;                                            // 0x012C(0x0010)
	unsigned char                                      UnknownData01[0x4];                                       // 0x013C(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.AESpawnSubsystem");
		return pStaticClass;
	}


	class AActor* SpawnUnit(const struct FSTSpawnParam& SpawnParam);
	bool PreCheck();
	int GetUnitConfigID(class AActor* Unit);
};


// Class AI.AIActionExecutionComponent
// 0x0008 (0x0158 - 0x0150)
class UAIActionExecutionComponent : public ULuaActorComponent
{
public:
	class ASTExtraBaseCharacter*                       MyPlayerPawn;                                             // 0x0150(0x0004) (ZeroConstructor, IsPlainOldData)
	class UMLAIControllerComponent*                    MyMLAIControllerComp;                                     // 0x0154(0x0004) (ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData)

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.AIActionExecutionComponent");
		return pStaticClass;
	}


	void SetFocusRotation(float InPitch, float InYaw, float InRoll);
	bool IsFreeCamera();
	class APickUpWrapperActor* GetPickActorWithID(int UId);
	void DoActionMove(bool IsRun, float DirectionX, float DirectionY, float DirectionZ);
	void DoActionFreeCamera(bool IsEnter, float InPitch, float InYaw, float InRoll);
};


// Class AI.AIPerceptionDynamicItemComponent
// 0x0020 (0x0170 - 0x0150)
class UAIPerceptionDynamicItemComponent : public ULuaActorComponent
{
public:
	TArray<struct FChildDynamicItem>                   ChildArray;                                               // 0x0150(0x000C) (Edit, ZeroConstructor)
	unsigned char                                      UnknownData00[0x4];                                       // 0x015C(0x0004) MISSED OFFSET
	struct FScriptDelegate                             GetDynamicItemDurabilityDelegate;                         // 0x0160(0x000C) (Edit, ZeroConstructor, InstancedReference)
	unsigned char                                      UnknownData01[0x4];                                       // 0x015C(0x0004) FIX WRONG TYPE SIZE OF PREVIOUS PROPERTY

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.AIPerceptionDynamicItemComponent");
		return pStaticClass;
	}

};


// Class AI.AISoundCollectionComponent
// 0x00E0 (0x0230 - 0x0150)
class UAISoundCollectionComponent : public ULuaActorComponent
{
public:
	unsigned char                                      UnknownData00[0x38];                                      // 0x0150(0x0038) MISSED OFFSET
	TMap<uint32_t, struct FCacheSoundState>            CacheWeaponSounds;                                        // 0x0188(0x0050) (ZeroConstructor)
	TMap<uint32_t, struct FCacheSoundState>            CacheVehicleSounds;                                       // 0x01C4(0x0050) (ZeroConstructor)
	unsigned char                                      UnknownData01[0x18];                                      // 0x0200(0x0018) MISSED OFFSET
	float                                              ClearStepSoundTime;                                       // 0x0218(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              ClearWeaponSoundTime;                                     // 0x021C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              ClearVehicleSoundTime;                                    // 0x0220(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                StepSoundMaxNum;                                          // 0x0224(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                WeaponSoundMaxNum;                                        // 0x0228(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                VehicleSoundMaxNum;                                       // 0x022C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.AISoundCollectionComponent");
		return pStaticClass;
	}


	void OnCollectionHearSound(ESoundType soundType, const struct FVector& InPos, class AActor* InSourceActor);
	TArray<struct FSoundState> GetCollectSoundInfo();
};


// Class AI.AIStateInfoComponent
// 0x0878 (0x0938 - 0x00C0)
class UAIStateInfoComponent : public UActorComponent
{
public:
	unsigned char                                      UnknownData00[0x38];                                      // 0x00C0(0x0038) MISSED OFFSET
	TMap<int, bool>                                    AvailableBackpacItemTypes;                                // 0x00F8(0x0050) (Edit, BlueprintVisible, ZeroConstructor)
	TMap<int, int>                                     GrenadeTypeConfig;                                        // 0x0134(0x0050) (Edit, BlueprintVisible, ZeroConstructor)
	float                                              VisibleAngle;                                             // 0x0170(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FVector                                     HeadOffset;                                               // 0x0174(0x000C) (Edit, BlueprintVisible, IsPlainOldData)
	float                                              NearByEnemyRange;                                         // 0x0180(0x0004) (Edit, BlueprintVisible, ZeroConstructor, Config, IsPlainOldData)
	float                                              FogWeatherRangeScale;                                     // 0x0184(0x0004) (Edit, BlueprintVisible, ZeroConstructor, Config, IsPlainOldData)
	int                                                NearByEnemyMaxNum;                                        // 0x0188(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               IsSearchNearItem;                                         // 0x018C(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x3];                                       // 0x018D(0x0003) MISSED OFFSET
	int                                                NearbyItemMaxNum;                                         // 0x0190(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                NearbyMaxBoxNum;                                          // 0x0194(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              NearbyAirDropBoxRangeInner;                               // 0x0198(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              NearbyAirDropBoxRangeOuter;                               // 0x019C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              NearbyDeathBoxRange;                                      // 0x01A0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              NearbyPickUpWrapperRange;                                 // 0x01A4(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              CacheNearbyItemRangeCoefficient;                          // 0x01A8(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              NearbyFindBuildingRange;                                  // 0x01AC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              ItemStateChangedRange;                                    // 0x01B0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               IsItemVisiable;                                           // 0x01B4(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               IsUseItemSpotLoc;                                         // 0x01B5(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData02[0x2];                                       // 0x01B6(0x0002) MISSED OFFSET
	float                                              NearbyObstacleRange;                                      // 0x01B8(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              NearbyThrownRange;                                        // 0x01BC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                NearbyThrownMaxNum;                                       // 0x01C0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData03[0x4];                                       // 0x01C4(0x0004) MISSED OFFSET
	int                                                NearbyDoorMaxNum;                                         // 0x01C8(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                NearbyVehicleRange;                                       // 0x01CC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, Config, IsPlainOldData)
	int                                                NearbyVehicleMaxNum;                                      // 0x01D0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              NearbyBulletHoleRange;                                    // 0x01D4(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                NearbyBulletHoleMaxNum;                                   // 0x01D8(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              NearbyDynamicItemsRange;                                  // 0x01DC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                NearbyDynamicItemsMaxNum;                                 // 0x01E0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData04[0x4];                                       // 0x01E4(0x0004) MISSED OFFSET
	struct FAIStateInfo                                CacheAIStateInfo;                                         // 0x01E8(0x02D8)
	struct FDiffAIStateInfo                            CacheDiffAIStateInfo;                                     // 0x04C0(0x0384)
	struct FRedZoneState                               CacheRedZoneInfo;                                         // 0x0844(0x0018)
	float                                              AirAttackTotalTime;                                       // 0x085C(0x0004) (ZeroConstructor, IsPlainOldData)
	bool                                               IsTouchedPlayer;                                          // 0x0860(0x0001) (ZeroConstructor, IsPlainOldData)
	bool                                               bIgnoreTreeAIWhenNoPlayerAround;                          // 0x0861(0x0001) (Edit, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData05[0x2];                                       // 0x0862(0x0002) MISSED OFFSET
	float                                              IgnoreTreeAIRadius;                                       // 0x0864(0x0004) (Edit, ZeroConstructor, IsPlainOldData)
	bool                                               bSendPlayerSimpleInfo;                                    // 0x0868(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData06[0x3];                                       // 0x0869(0x0003) MISSED OFFSET
	uint32_t                                           FrameNo;                                                  // 0x086C(0x0004) (ZeroConstructor, IsPlainOldData)
	class UAirAttackComponent*                         AirAttackComp;                                            // 0x0870(0x0004) (ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData)
	class APawn*                                       MyOwnerPawn;                                              // 0x0874(0x0004) (ZeroConstructor, IsPlainOldData)
	class ABattleRoyaleGameModeBase*                   MyGameMode;                                               // 0x0878(0x0004) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData07[0x48];                                      // 0x087C(0x0048) MISSED OFFSET
	TArray<struct FVehicleDamageInfo>                  VehicleDamageInfo;                                        // 0x08C4(0x000C) (ZeroConstructor)
	TMap<int, class APickUpWrapperActor*>              CacheAINearByItem;                                        // 0x08D0(0x0050) (ZeroConstructor)
	struct FCacheNearbyItemState                       CacheNearbyItemState;                                     // 0x090C(0x001C)
	class UMLAIControllerComponent*                    MyMLAIControllerComp;                                     // 0x0928(0x0004) (ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData)
	uint32_t                                           CacheModeMapId;                                           // 0x092C(0x0004) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData08[0x8];                                       // 0x0930(0x0008) MISSED OFFSET

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.AIStateInfoComponent");
		return pStaticClass;
	}


	TArray<struct FItemStateData> QueryItemStates(int MaxBoxNum, int MaxItemNum, float AirDropBoxRangeInner, float AirDropBoxRangeOuter, float DeathBoxRange, float PickUpWrapperRange, float FindBuildingRange, bool InIsUseItemSpotLoc);
	void OnVehicleDamageInfo(class AController* InstigatorController, class AController* VictimController, int DamageTypeId, float Damage, bool bIsFatalHealthCost, class AActor* DamageCauser, class AActor* VictimVehicle);
	void OnItemStateChanged(const struct FVector& Location);
	void OnAIStateRequestEnd();
	void OnAirAttackInfo(TEnumAsByte<EAirAttackInfo> airattacktype, int waveIndex, const struct FAirAttackOrder& InAirAttackOrder, const struct FVector& InAirAttackArea);
	bool IsAvailableBackpacItemType(const struct FItemDefineID& DefineID);
	bool HasPlayerAround();
	struct FVector GetViewForwardVector(class ACharacter* InCharacter);
	struct FVehicleState GetVehicleStatus(class ASTExtraVehicleBase* InVehicle, class ASTExtraBaseCharacter* PawnInCar);
	struct FTLogAIShootInfo GetTLogAIShootInfo();
	TArray<struct FSoundState> GetSoundInfo();
	struct FProgressBarState GetProgressBarState();
	struct FAIPlayerInteractInfo GetPlayerInteractInfo();
	class APickUpWrapperActor* GetPickActorWithID(int UId);
	TArray<struct FObstacleState> GetObstaclesState(float Range);
	TArray<struct FVehicleState> GetNearbyVehicles(class ASTExtraBaseCharacter* InPawn);
	uint32_t GetFrameNo();
	TArray<struct FDoorState> GetDoorsState(float Range, int MaxNum);
	struct FDiffAIStateInfo GetDiffAIStateInfo();
	struct FAIDamageSources GetDamageSources();
	struct FCameraState GetCameraState(class ASTExtraBaseCharacter* InCharacter);
	TArray<struct FAIStateInfo> GetAllPlayerStateInfo();
	struct FAIStateInfo GetAIStateInfoInternal();
	struct FAIStateInfo GetAIStateInfo();
	TArray<struct FAIBackpackItem> GetAIPlayerBackpackItems(class ABaseAIController* InController);
	TArray<struct FAINearbyThrown> GetAINearbyThrownState(class ASTExtraBaseCharacter* InCharacter, float InRange, float InCheckAngle, int MaxNum);
	void ClearVehicleDamageInfo();
	void ClearPlayerInteractInfo();
	void ClearDamageSources();
};


// Class AI.CustomDamageEventComponent
// 0x00F0 (0x0240 - 0x0150)
class UCustomDamageEventComponent : public ULuaActorComponent
{
public:
	unsigned char                                      UnknownData00[0x8];                                       // 0x0150(0x0008) MISSED OFFSET
	unsigned char                                      UnknownData01[0x28];                                      // 0x0150(0x0028) UNKNOWN PROPERTY: SoftObjectProperty AI.CustomDamageEventComponent.EventDataTable
	float                                              ActorSpawnGlobalCooldown;                                 // 0x0180(0x0004) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	struct FScriptMulticastDelegate                    OnThrowBox;                                               // 0x0184(0x000C) (ZeroConstructor, InstancedReference, BlueprintAssignable)
	unsigned char                                      UnknownData02[0x4];                                       // 0x0190(0x0004) MISSED OFFSET
	float                                              OwnerHealthPercentage;                                    // 0x0194(0x0004) (Net, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData03[0xC];                                       // 0x0198(0x000C) MISSED OFFSET
	TArray<struct FTriggeredCustomDamageEvent>         ClientEvents;                                             // 0x01A4(0x000C) (Net, ZeroConstructor)
	unsigned char                                      UnknownData04[0x50];                                      // 0x01B0(0x0050) MISSED OFFSET
	TMap<struct FName, class UObject*>                 CacheUObjectMap;                                          // 0x0200(0x0050) (ZeroConstructor)
	unsigned char                                      UnknownData05[0x4];                                       // 0x023C(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.CustomDamageEventComponent");
		return pStaticClass;
	}


	void OnRep_ClientEvents();
};


// Class AI.CharacterCustomDamageEventComponent
// 0x0000 (0x0240 - 0x0240)
class UCharacterCustomDamageEventComponent : public UCustomDamageEventComponent
{
public:

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.CharacterCustomDamageEventComponent");
		return pStaticClass;
	}


	void OnTakeDamageEvent(float Damage, const struct FDamageEvent& DamageEvent, class AActor* Victim, class AActor* Causer);
};


// Class AI.MLAIControllerComponent
// 0x00F8 (0x01B8 - 0x00C0)
class UMLAIControllerComponent : public UActorComponent
{
public:
	class UClass*                                      AISoundCollectCompClass;                                  // 0x00C0(0x0004) (Edit, ZeroConstructor, IsPlainOldData)
	class UClass*                                      AIStateInfoCompClass;                                     // 0x00C4(0x0004) (Edit, ZeroConstructor, IsPlainOldData)
	class UAIActionExecutionComponent*                 AIActionExecutionComp;                                    // 0x00C8(0x0004) (Edit, BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData)
	class UAIStateInfoComponent*                       AIStateInfoComp;                                          // 0x00CC(0x0004) (Edit, BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData)
	class UAISoundCollectionComponent*                 AISoundCollectComp;                                       // 0x00D0(0x0004) (Edit, BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData)
	float                                              HearRadius;                                               // 0x00D4(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	TMap<TEnumAsByte<ESTEPoseState>, struct FCameraViewPitchLimitData> CameraViewPitchLimitDataMap;                              // 0x00D8(0x0050) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FVector                                     PrePos;                                                   // 0x0114(0x000C) (IsPlainOldData)
	float                                              PreTickTime;                                              // 0x0120(0x0004) (ZeroConstructor, IsPlainOldData)
	class ANewFakePlayerAIController*                  MyController;                                             // 0x0124(0x0004) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x14];                                      // 0x0128(0x0014) MISSED OFFSET
	float                                              FindNavLocationRadius;                                    // 0x013C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                MaxNavLocationFindTimes;                                  // 0x0140(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               bUseLerpRotation;                                         // 0x0144(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x3];                                       // 0x0145(0x0003) MISSED OFFSET
	float                                              LerpRotationThreshold;                                    // 0x0148(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               IsForceTargetRotation;                                    // 0x014C(0x0001) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData02[0x3];                                       // 0x014D(0x0003) MISSED OFFSET
	float                                              FirstLerpRotationDeltaTime;                               // 0x0150(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              FreeCameraTurnVelocity;                                   // 0x0154(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData03[0x4];                                       // 0x0158(0x0004) MISSED OFFSET
	bool                                               IsModifyDamageLuaOverride;                                // 0x015C(0x0001) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData04[0x3];                                       // 0x015D(0x0003) MISSED OFFSET
	float                                              RatingDamageScaleLuaOverride;                             // 0x0160(0x0004) (ZeroConstructor, IsPlainOldData)
	bool                                               bShouldSendVehicleInfo;                                   // 0x0164(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData05[0x53];                                      // 0x0165(0x0053) MISSED OFFSET

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.MLAIControllerComponent");
		return pStaticClass;
	}


	void UnBindDelegates(bool IsEndPlay);
	void SetLuaAIParamConfigString(const struct FString& InAIParamConfigString);
	void RestartFightBehaviorTree();
	bool IsFreeCamera();
	struct FRotator GetViewRotation();
	struct FVector GetViewForwardVector();
	class UAIStateInfoComponent* GetAIStateInfoComp();
	class UAIActionExecutionComponent* GetAIActionExecutionComp();
	void DoActionFreeCamera(bool IsEnter, float InPitch, float InYaw, float InRoll);
	bool CheckCameraViewPitchLimit(struct FRotator* InOutTargetRot);
	void BindDelegates();
};


// Class AI.MLAISubSystem
// 0x01A8 (0x01C8 - 0x0020)
class UMLAISubSystem : public UWorldSubsystem
{
public:
	struct FScriptMulticastDelegate                    OnAIStateRequestEnd;                                      // 0x0020(0x000C) (ZeroConstructor, InstancedReference)
	TMap<uint32_t, struct FAIPlayerState>              CacheAIPlayerStates;                                      // 0x002C(0x0050) (ZeroConstructor)
	TMap<uint32_t, struct FAIPlayerInteractInfo>       CachePlayerDamageInfo;                                    // 0x0068(0x0050) (ZeroConstructor)
	TMap<uint32_t, struct FVehicleDamageInfoContainer> CacheVehicleDamageInfo;                                   // 0x00A4(0x0050) (ZeroConstructor)
	int                                                MaxCacheDamageInfoNum;                                    // 0x00E0(0x0004) (ZeroConstructor, IsPlainOldData)
	TMap<uint32_t, struct FAIPlayerWeapon>             CacheAIPlayerWeapons;                                     // 0x00E4(0x0050) (ZeroConstructor)
	TMap<uint32_t, struct FAIPlayerEquipment>          CacheAIPlayerEquipments;                                  // 0x0120(0x0050) (ZeroConstructor)
	TArray<class UAIStateInfoComponent*>               AIStateInfoComps;                                         // 0x015C(0x000C) (ExportObject, ZeroConstructor)
	TArray<struct FBulletHoleRecordInfo>               CacheBulletHoles;                                         // 0x0168(0x000C) (ZeroConstructor)
	TArray<struct FSpecialZoneState>                   CacheSpecialZones;                                        // 0x0174(0x000C) (ZeroConstructor)
	unsigned char                                      UnknownData00[0xC];                                       // 0x0180(0x000C) MISSED OFFSET
	TMap<class AActor*, class ASpecialZoneActor*>      CacheSpecialZoneParents;                                  // 0x018C(0x0050) (ZeroConstructor)

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.MLAISubSystem");
		return pStaticClass;
	}


	void StartRequestCache();
	void SetSpecialZoneCustomState(class AActor* InParent, int InCustomState);
	void OnVehicleDamageInfo(class AController* InstigatorController, class AController* VictimController, int DamageTypeId, float Damage, bool bIsFatalHealthCost, class AActor* DamageCauser, class AActor* VictimVehicle);
	void OnPlayerDamageInfo(class ASTExtraPlayerState* InstigatorPlayerState, class ASTExtraPlayerState* VictimPlayerState, float Damage, const struct FDamageEvent& DamageEvent, float DamageBeforeCalArmor, bool bIsFatalHealthCost, class AActor* DamageCauser);
	void OnItemStateChanged(const struct FVector& Location);
	bool IsAIBotGame();
	void EndRequestCache();
};


// Class AI.MLAITrainingComponent
// 0x0010 (0x00D0 - 0x00C0)
class UMLAITrainingComponent : public UActorComponent
{
public:
	unsigned char                                      UnknownData00[0x10];                                      // 0x00C0(0x0010) MISSED OFFSET

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.MLAITrainingComponent");
		return pStaticClass;
	}


	void StopRunnable();
	void SendAIStateRequest(TArray<unsigned char> Packet);
	bool IsRequestAIState();
	void InitRunnable(float InStartCollectingInterval, float InSendInterval, float InTimeOutInterval);
	void EndRequestAIState();
};


// Class AI.SpecialZoneShapeComponent
// 0x0000 (0x0610 - 0x0610)
class USpecialZoneShapeComponent : public UPrimitiveComponent
{
public:

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.SpecialZoneShapeComponent");
		return pStaticClass;
	}

};


// Class AI.SpecialZoneActor
// 0x0018 (0x0308 - 0x02F0)
class ASpecialZoneActor : public AActor
{
public:
	float                                              Radius;                                                   // 0x02F0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                Type;                                                     // 0x02F4(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                CustomState;                                              // 0x02F8(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	class USpecialZoneShapeComponent*                  SpecialZoneShapeComponent;                                // 0x02FC(0x0004) (Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData)
	class AActor*                                      CacheParentActor;                                         // 0x0300(0x0004) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x4];                                       // 0x0304(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.SpecialZoneActor");
		return pStaticClass;
	}


	void UpdateCustomState(int InCustomState);
	struct FSpecialZoneState GetSpecialZoneState();
};


// Class AI.STStrategyLocation_Range
// 0x0038 (0x00E0 - 0x00A8)
class USTStrategyLocation_Range : public USTStrategyLocation
{
public:
	float                                              Range;                                                    // 0x00A8(0x0004) (Edit, ZeroConstructor, IsPlainOldData)
	int                                                MaxTryTimes;                                              // 0x00AC(0x0004) (Edit, ZeroConstructor, IsPlainOldData)
	unsigned char                                      bCheckPlayerSight : 1;                                    // 0x00B0(0x0001) (Edit)
	unsigned char                                      UnknownData00[0x3];                                       // 0x00B1(0x0003) MISSED OFFSET
	float                                              PlayerViewDistance;                                       // 0x00B4(0x0004) (Edit, ZeroConstructor, IsPlainOldData)
	TEnumAsByte<ECollisionChannel>                     CollisionChannel;                                         // 0x00B8(0x0001) (Edit, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x3];                                       // 0x00B9(0x0003) MISSED OFFSET
	float                                              MaxLocationTraceHeightZ;                                  // 0x00BC(0x0004) (Edit, ZeroConstructor, IsPlainOldData)
	TArray<struct FSpawnArea>                          CustomAreas;                                              // 0x00C0(0x000C) (Edit, ZeroConstructor)
	unsigned char                                      UnknownData02[0x14];                                      // 0x00CC(0x0014) MISSED OFFSET

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.STStrategyLocation_Range");
		return pStaticClass;
	}


	void ModifyBaseLocation(const struct FVector& InLocation);
	bool GetSpawnLocation(class AActor* Requester, int ReferenceCount, TArray<struct FSpawnSpotInfo>* OutArr);
	void AddSpawnArea(const struct FSpawnArea& NewArea, bool ForceAdd);
	void ActivateStrategy(class ASTSpawnerBase* Owner);
};


// Class AI.STStrategySpecies_Candidate
// 0x0000 (0x00D0 - 0x00D0)
class USTStrategySpecies_Candidate : public USTStrategySpecies
{
public:

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.STStrategySpecies_Candidate");
		return pStaticClass;
	}


	TArray<struct FUnitConfig> Supply(int ReferencedCount, TArray<struct FSpawnSpotInfo> SpotSpecies);
	void ActivateStrategy(class ASTSpawnerBase* Owner);
};


// Class AI.STStrategySpecies_Lua
// 0x0000 (0x00D0 - 0x00D0)
class USTStrategySpecies_Lua : public USTStrategySpecies
{
public:

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.STStrategySpecies_Lua");
		return pStaticClass;
	}


	TArray<struct FUnitConfig> Supply(int ReferencedCount, TArray<struct FSpawnSpotInfo> SpotSpecies);
	void LuaSupply(int ReferencedCount);
};


// Class AI.STStrategyTiming_Event
// 0x0018 (0x00C8 - 0x00B0)
class USTStrategyTiming_Event : public USTStrategyTiming
{
public:
	struct FString                                     EventId;                                                  // 0x00B0(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     EventName;                                                // 0x00BC(0x000C) (Edit, BlueprintVisible, ZeroConstructor)

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.STStrategyTiming_Event");
		return pStaticClass;
	}


	void TickStrategy(float DeltaTime);
	void OnSpawnEventBroadcast();
	void ActivateStrategy(class ASTSpawnerBase* Owner);
};


// Class AI.VehicleAIUserComponent
// 0x0000 (0x0170 - 0x0170)
class UVehicleAIUserComponent : public UVehicleUserComponentBase
{
public:

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.VehicleAIUserComponent");
		return pStaticClass;
	}


	void ServerVehicleLeanOut(bool bLeanOut);
	void ServerExitVehicle();
	void ServerEnterVehicle(class ASTExtraVehicleBase* InVehicle, unsigned char SeatType);
	void ServerChangeVehicleSeat(int InSeatIndex);
	void MulticastExitVehicle();
	void MulticastEnterVehicle(class ASTExtraVehicleBase* InVehicle, class ASTExtraPlayerCharacter* Pawn, bool bSuccess, unsigned char SeatType, int SeatIndex);
	void MulticastChangeVehicleSeat(int InSeatIndex);
};


// Class AI.VehicleCustomDamageEventComponent
// 0x0000 (0x0240 - 0x0240)
class UVehicleCustomDamageEventComponent : public UCustomDamageEventComponent
{
public:

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.VehicleCustomDamageEventComponent");
		return pStaticClass;
	}


	void OnVehicleHPFuelChanged(float HP, float Fuel);
};


}

