#pragma once

// PUBG MOBILE 2.5.0 SDK generated by Huy#3877 

namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_SocialCardDate_type.BP_STRUCT_SocialCardDate_type
// 0x0010
struct FBP_STRUCT_SocialCardDate_type
{
	struct FString                                     Date_0_28B039C03A0BED89791588A502B13BA5;                  // 0x0000(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                ID_1_72C45D802E3B21C6496F24DD0302B144;                    // 0x000C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
};

}

