#pragma once

// PUBG MOBILE 2.7.0 SDK generated by Huy#3877 

namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_ParamConfig_type.BP_STRUCT_ParamConfig_type
// 0x0010
struct FBP_STRUCT_ParamConfig_type
{
	struct FString                                     ParamName_0_3E5093C0622417BF51FDE5CD07CE52A5;             // 0x0000(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                ParamValue_1_11E112C00B831E5D3BCE331C0CED2AC5;            // 0x000C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
};

}

