#pragma once

// PUBG MOBILE 2.7.0 SDK generated by Huy#3877 

namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_NicknameEffectCfg_type.BP_STRUCT_NicknameEffectCfg_type
// 0x0020
struct FBP_STRUCT_NicknameEffectCfg_type
{
	struct FString                                     BPPath_0_1677EE002732F49467F1C35B0F55B538;                // 0x0000(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                GetDescID_1_02E97140358606837938BFA005756814;             // 0x000C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     GetJumpUrl_2_5222E20067D8F9604E2D26D40C3BA0EC;            // 0x0010(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                ID_3_7F62E9802F499BE43B0E4CD700DD9FF4;                    // 0x001C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
};

}

