#pragma once

// PUBG MOBILE 2.7.0 SDK generated by Huy#3877 

namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_SettingRedPointConfig_type.BP_STRUCT_SettingRedPointConfig_type
// 0x0020
struct FBP_STRUCT_SettingRedPointConfig_type
{
	int                                                ID_0_06917F004C4564346198F4370B9E4FE4;                    // 0x0000(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     Key_1_1C0D860066C4AE720A1C3C1809E50279;                   // 0x0004(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     Name_2_3127FC0061DAD35C6C1B6F630E507DA5;                  // 0x0010(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                Tab_4_0AC1C1806018E11E0A1DE7D209E4E9C2;                   // 0x001C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
};

}

