#pragma once

// PUBG MOBILE 2.7.0 SDK generated by Huy#3877 

namespace SDK
{
//---------------------------------------------------------------------------
//Classes
//---------------------------------------------------------------------------

// Class AI.AESpawner
// 0x0028 (0x0430 - 0x0408)
class AAESpawner : public ASTSpawnerBase
{
public:
	unsigned char                                      bEnableTeamAI : 1;                                        // 0x0408(0x0001) (Edit, BlueprintVisible)
	unsigned char                                      UnknownData00[0x3];                                       // 0x0409(0x0003) MISSED OFFSET
	TArray<class UClass*>                              TeamAIClasses;                                            // 0x040C(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                SpawnerCampItemID;                                        // 0x0418(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                SpawnerTeamID;                                            // 0x041C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	TEnumAsByte<EBotCategray>                          SpeciesCategory;                                          // 0x0420(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x3];                                       // 0x0421(0x0003) MISSED OFFSET
	TArray<class UActorComponent*>                     TeamAIComponents;                                         // 0x0424(0x000C) (ExportObject, ZeroConstructor)

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.AESpawner");
		return pStaticClass;
	}


	void SwitchTeamAI(bool bEnable);
	void OnUnitSpawned(uint32_t InSpawnerID, class APawn* AIPawn, int ConfigId);
	void OnSpawnTimingRipe(bool IsRipe);
	void OnOwnedMobDead(class ASTExtraSimpleCharacter* DeadCharacter, class AController* Killer, class AActor* DamageCauser, const struct FHitResult& KillingHitInfo, const struct FVector& KillingHitImpulseDir, class UClass* KillingHitDamageType);
	void OnOwnedFakePlayerDead(class ASTExtraBaseCharacter* DeadCharacter, class AController* Killer, class AActor* DamageCauser, const struct FHitResult& KillingHitInfo, const struct FVector& KillingHitImpulseDir, class UClass* KillingHitDamageType);
	TEnumAsByte<EBotCategray> GetSpeciesCategory();
	float GetSpawnerTeamID();
	int GenerateParamID(int ConfigId, int BaseParamID);
	void DeactivateSpawner();
	void BPOnUnitSpawned(class APawn* AIPawn, int ConfigId);
	void ActivateSpawner();
};


// Class AI.AESpawnSubsystem
// 0x0080 (0x0160 - 0x00E0)
class UAESpawnSubsystem : public USTSpawnSubsystem
{
public:
	unsigned char                                      UnknownData00[0x4C];                                      // 0x00E0(0x004C) MISSED OFFSET
	struct FFakePlayerParams                           CacheFPParams;                                            // 0x012C(0x0010)
	struct FAIPlayerParams                             CacheAIPParams;                                           // 0x013C(0x000C)
	struct FVehicleParams                              CacheVehicleParams;                                       // 0x0148(0x0014)
	unsigned char                                      UnknownData01[0x4];                                       // 0x015C(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.AESpawnSubsystem");
		return pStaticClass;
	}


	class AActor* SpawnUnit(const struct FSTSpawnParam& SpawnParam);
	bool PreCheck();
	int GetUnitConfigID(class AActor* Unit);
	bool CheckCategoryLimit(class ASTSpawnerBase* Spawner);
};


// Class AI.AIActionExecutionComponent
// 0x0010 (0x0160 - 0x0150)
class UAIActionExecutionComponent : public ULuaActorComponent
{
public:
	class ANewFakePlayerAIController*                  MyAIController;                                           // 0x0150(0x0004) (ZeroConstructor, IsPlainOldData)
	class ASTExtraPlayerController*                    MyPlayerController;                                       // 0x0154(0x0004) (ZeroConstructor, IsPlainOldData)
	class ASTExtraBaseCharacter*                       MyPlayerPawn;                                             // 0x0158(0x0004) (ZeroConstructor, IsPlainOldData)
	class UMLAIControllerComponent*                    MyMLAIControllerComp;                                     // 0x015C(0x0004) (ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData)

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.AIActionExecutionComponent");
		return pStaticClass;
	}


	void UseItem(int ItemID, int WeaponSlot);
	void SwapAttachmentItem(int ItemID, int SourceWeaponSlot, int TargetWeaponSlot);
	void SetGrenadeLastSelectID(int WeaponId);
	void SetFocusRotation(float InPitch, float InYaw, float InRoll);
	void SetCurShootingPose();
	void RescueTarget(class ASTExtraBaseCharacter* RescueCharacter);
	void OpenDoor();
	bool IsValid();
	bool IsFreeCamera();
	class APickUpWrapperActor* GetPickActorWithID(int UID);
	class ASTExtraBaseCharacter* GetOwnerBaseCharacter();
	class UBackpackComponent* GetBackpackComponent();
	void DropItem(int ItemID, int Count);
	void DoActionMove(bool IsRun, float DirectionX, float DirectionY, float DirectionZ);
	void DoActionFreeCamera(bool IsEnter, float InPitch, float InYaw, float InRoll);
	void DisuseItem(int ItemID, int WeaponSlot);
	void CloseDoor();
};


// Class AI.AIPerceptionDynamicItemComponent
// 0x0020 (0x0170 - 0x0150)
class UAIPerceptionDynamicItemComponent : public ULuaActorComponent
{
public:
	TArray<struct FChildDynamicItem>                   ChildArray;                                               // 0x0150(0x000C) (Edit, ZeroConstructor)
	unsigned char                                      UnknownData00[0x4];                                       // 0x015C(0x0004) MISSED OFFSET
	struct FScriptDelegate                             GetDynamicItemDurabilityDelegate;                         // 0x0160(0x000C) (Edit, ZeroConstructor, InstancedReference)
	unsigned char                                      UnknownData01[0x4];                                       // 0x015C(0x0004) FIX WRONG TYPE SIZE OF PREVIOUS PROPERTY

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.AIPerceptionDynamicItemComponent");
		return pStaticClass;
	}

};


// Class AI.AISoundCollectionComponent
// 0x0130 (0x0280 - 0x0150)
class UAISoundCollectionComponent : public ULuaActorComponent
{
public:
	unsigned char                                      UnknownData00[0x38];                                      // 0x0150(0x0038) MISSED OFFSET
	TMap<uint32_t, struct FCacheSoundState>            CacheWeaponSounds;                                        // 0x0188(0x0050) (ZeroConstructor)
	TMap<uint32_t, struct FCacheSoundState>            CacheVehicleSounds;                                       // 0x01C4(0x0050) (ZeroConstructor)
	TMap<uint32_t, struct FCacheSoundState>            CacheGrenadeSounds;                                       // 0x0200(0x0050) (ZeroConstructor)
	unsigned char                                      UnknownData01[0x1C];                                      // 0x023C(0x001C) MISSED OFFSET
	float                                              ClearStepSoundTime;                                       // 0x0258(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              ClearWeaponSoundTime;                                     // 0x025C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              ClearVehicleSoundTime;                                    // 0x0260(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              ClearGrenadeSoundTime;                                    // 0x0264(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                StepSoundMaxNum;                                          // 0x0268(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                WeaponSoundMaxNum;                                        // 0x026C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                VehicleSoundMaxNum;                                       // 0x0270(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                GrenadeSoundMaxNum;                                       // 0x0274(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	class AController*                                 OwnerController;                                          // 0x0278(0x0004) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData02[0x4];                                       // 0x027C(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.AISoundCollectionComponent");
		return pStaticClass;
	}


	void OnCollectionHearSound(ESoundType soundType, const struct FVector& InPos, class AActor* InSourceActor);
	void OnAISoundManagerHear(class AActor* InTargetActor, ESoundType soundType, const struct FVector& InPos, class AActor* InSourceActor);
	TArray<struct FSoundState> GetCollectSoundInfo();
};


// Class AI.AIStateInfoComponent
// 0x0AE0 (0x0BA0 - 0x00C0)
class UAIStateInfoComponent : public UActorComponent
{
public:
	unsigned char                                      UnknownData00[0x38];                                      // 0x00C0(0x0038) MISSED OFFSET
	TMap<int, bool>                                    AvailableBackpacItemTypes;                                // 0x00F8(0x0050) (Edit, BlueprintVisible, ZeroConstructor)
	TMap<int, int>                                     GrenadeTypeConfig;                                        // 0x0134(0x0050) (Edit, BlueprintVisible, ZeroConstructor)
	float                                              VisibleAngle;                                             // 0x0170(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FVector                                     HeadOffset;                                               // 0x0174(0x000C) (Edit, BlueprintVisible, IsPlainOldData)
	float                                              NearByEnemyRange;                                         // 0x0180(0x0004) (Edit, BlueprintVisible, ZeroConstructor, Config, IsPlainOldData)
	float                                              FogWeatherRangeScale;                                     // 0x0184(0x0004) (Edit, BlueprintVisible, ZeroConstructor, Config, IsPlainOldData)
	int                                                NearByEnemyMaxNum;                                        // 0x0188(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               IsSearchNearItem;                                         // 0x018C(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x3];                                       // 0x018D(0x0003) MISSED OFFSET
	int                                                NearbyItemMaxNum;                                         // 0x0190(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                NearbyMaxBoxNum;                                          // 0x0194(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              NearbyAirDropBoxRangeInner;                               // 0x0198(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              NearbyAirDropBoxRangeOuter;                               // 0x019C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              NearbyDeathBoxRange;                                      // 0x01A0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              NearbyPickUpWrapperRange;                                 // 0x01A4(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              CacheNearbyItemRangeCoefficient;                          // 0x01A8(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                NearbyMaxTreasureChestNum;                                // 0x01AC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              NearbyTreasureChestRange;                                 // 0x01B0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                NearbyMaxWeedNum;                                         // 0x01B4(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              NearbyWeedRange;                                          // 0x01B8(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              NearbyFindBuildingRange;                                  // 0x01BC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              ItemStateChangedRange;                                    // 0x01C0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               IsItemVisiable;                                           // 0x01C4(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               IsUseItemSpotLoc;                                         // 0x01C5(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData02[0x2];                                       // 0x01C6(0x0002) MISSED OFFSET
	float                                              NearbyObstacleRange;                                      // 0x01C8(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              NearbyThrownRange;                                        // 0x01CC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              NearbySmokeRange;                                         // 0x01D0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                NearbyThrownMaxNum;                                       // 0x01D4(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData03[0x4];                                       // 0x01D8(0x0004) MISSED OFFSET
	int                                                NearbyDoorMaxNum;                                         // 0x01DC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                NearbyVehicleRange;                                       // 0x01E0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, Config, IsPlainOldData)
	int                                                NearbyVehicleMaxNum;                                      // 0x01E4(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              NearbyBulletHoleRange;                                    // 0x01E8(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                NearbyBulletHoleMaxNum;                                   // 0x01EC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              NearbyDynamicItemsRange;                                  // 0x01F0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                NearbyDynamicItemsMaxNum;                                 // 0x01F4(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FAIStateInfo                                CacheAIStateInfo;                                         // 0x01F8(0x0470)
	struct FDiffAIStateInfo                            CacheDiffAIStateInfo;                                     // 0x0668(0x0400)
	struct FRedZoneState                               CacheRedZoneInfo;                                         // 0x0A68(0x0030)
	float                                              AirAttackTotalTime;                                       // 0x0A98(0x0004) (ZeroConstructor, IsPlainOldData)
	bool                                               IsTouchedPlayer;                                          // 0x0A9C(0x0001) (ZeroConstructor, IsPlainOldData)
	bool                                               bIgnoreTreeAIWhenNoPlayerAround;                          // 0x0A9D(0x0001) (Edit, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData04[0x2];                                       // 0x0A9E(0x0002) MISSED OFFSET
	float                                              IgnoreTreeAIRadius;                                       // 0x0AA0(0x0004) (Edit, ZeroConstructor, IsPlainOldData)
	uint32_t                                           FrameNo;                                                  // 0x0AA4(0x0004) (ZeroConstructor, IsPlainOldData)
	bool                                               IsCacheDiffData;                                          // 0x0AA8(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               UseBodyTPPCamera;                                         // 0x0AA9(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData05[0x2];                                       // 0x0AAA(0x0002) MISSED OFFSET
	class ASTExtraPlayerController*                    MyPlayerController;                                       // 0x0AAC(0x0004) (ZeroConstructor, IsPlainOldData)
	class AController*                                 OwnerController;                                          // 0x0AB0(0x0004) (ZeroConstructor, IsPlainOldData)
	class ANewFakePlayerAIController*                  MyAIController;                                           // 0x0AB4(0x0004) (ZeroConstructor, IsPlainOldData)
	class UAirAttackComponent*                         AirAttackComp;                                            // 0x0AB8(0x0004) (ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData)
	class UAIActingComponent*                          AIActingComp;                                             // 0x0ABC(0x0004) (ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData)
	class APawn*                                       MyOwnerPawn;                                              // 0x0AC0(0x0004) (ZeroConstructor, IsPlainOldData)
	class ABattleRoyaleGameModeBase*                   MyGameMode;                                               // 0x0AC4(0x0004) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData06[0x60];                                      // 0x0AC8(0x0060) MISSED OFFSET
	TArray<struct FVehicleDamageInfo>                  VehicleDamageInfo;                                        // 0x0B28(0x000C) (ZeroConstructor)
	TMap<int, class APickUpWrapperActor*>              CacheAINearByItem;                                        // 0x0B34(0x0050) (ZeroConstructor)
	struct FCacheNearbyItemState                       CacheNearbyItemState;                                     // 0x0B70(0x001C)
	class UMLAIControllerComponent*                    MyMLAIControllerComp;                                     // 0x0B8C(0x0004) (ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData)
	uint32_t                                           CacheModeMapId;                                           // 0x0B90(0x0004) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData07[0xC];                                       // 0x0B94(0x000C) MISSED OFFSET

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.AIStateInfoComponent");
		return pStaticClass;
	}


	TArray<struct FItemStateData> QueryItemStates(int MaxBoxNum, int MaxItemNum, float AirDropBoxRangeInner, float AirDropBoxRangeOuter, float DeathBoxRange, float PickUpWrapperRange, float FindBuildingRange, bool InIsUseItemSpotLoc, int MaxTreasureChestNum, float TreasureChestRange, int MaxWeedNum, float WeedRange);
	void OnVehicleDamageInfo(class AController* InstigatorController, class AController* VictimController, int DamageTypeId, float Damage, bool bIsFatalHealthCost, class AActor* DamageCauser, class AActor* VictimVehicle);
	void OnItemStateChanged(const struct FVector& Location);
	void OnAIStateRequestEnd();
	void OnAirAttackInfo(TEnumAsByte<EAirAttackInfo> airattacktype, int waveIndex, const struct FAirAttackOrder& InAirAttackOrder, const struct FVector& InAirAttackArea);
	bool IsValid();
	bool IsAvailableBackpacItemType(const struct FItemDefineID& DefineID);
	bool HasPlayerAround();
	struct FVector GetViewForwardVector(class ACharacter* InCharacter);
	static struct FVehicleState GetVehicleStatus(class ASTExtraVehicleBase* InVehicle, class ASTExtraBaseCharacter* PawnInCar);
	struct FTLogAIShootInfo GetTLogAIShootInfo();
	struct FAIStateInfo GetTeammatePlayerStateInfo(class ASTExtraBaseCharacter* InCharacter, TArray<struct FString> InWhiteList);
	TArray<struct FSoundState> GetSoundInfo();
	struct FProgressBarState GetProgressBarState();
	struct FAIPlayerInteractInfo GetPlayerInteractInfo();
	class APickUpWrapperActor* GetPickActorWithID(int UID);
	class ASTExtraBaseCharacter* GetOwnerBaseCharacter();
	TArray<struct FObstacleState> GetObstaclesState(class ASTExtraBaseCharacter* InPawn, float Range);
	TArray<struct FVehicleState> GetNearbyVehicles(class ASTExtraBaseCharacter* InPawn);
	uint32_t GetFrameNo();
	TArray<struct FDoorState> GetDoorsState(float Range, int MaxNum);
	static struct FDiffAllPlayerInfoGeneral GetDiffAllPlayerStateInfoGeneral(class UWorld* InWorld, bool bNeedDebugInfo);
	struct FDiffAIStateInfoGeneral GetDiffAIStateInfoGeneral();
	struct FDiffAIStateInfo GetDiffAIStateInfo();
	struct FAIDamageSources GetDamageSources();
	struct FCameraState GetCameraState(class ASTExtraBaseCharacter* InCharacter);
	static TArray<struct FAIStateInfo> GetAllPlayerStateInfo(class UWorld* InWorld, bool bNeedUpdateCache);
	struct FAIStateInfo GetAIStateInfoInternal();
	struct FAIStateInfo GetAIStateInfo();
	TArray<struct FAIBackpackItem> GetAIPlayerBackpackItems();
	TArray<struct FAINearbyThrown> GetAINearbyThrownState(class ASTExtraBaseCharacter* InCharacter, float InRange, float InCheckAngle, int MaxNum, float InSmokeRange);
	void ClearVehicleDamageInfo();
	void ClearPlayerInteractInfo();
	void ClearDamageSources();
};


// Class AI.CustomDamageEventComponent
// 0x00F0 (0x0240 - 0x0150)
class UCustomDamageEventComponent : public ULuaActorComponent
{
public:
	unsigned char                                      UnknownData00[0x8];                                       // 0x0150(0x0008) MISSED OFFSET
	unsigned char                                      UnknownData01[0x28];                                      // 0x0150(0x0028) UNKNOWN PROPERTY: SoftObjectProperty AI.CustomDamageEventComponent.EventDataTable
	float                                              ActorSpawnGlobalCooldown;                                 // 0x0180(0x0004) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	struct FScriptMulticastDelegate                    OnThrowBox;                                               // 0x0184(0x000C) (ZeroConstructor, InstancedReference, BlueprintAssignable)
	unsigned char                                      UnknownData02[0x4];                                       // 0x0190(0x0004) MISSED OFFSET
	float                                              OwnerHealthPercentage;                                    // 0x0194(0x0004) (Net, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData03[0xC];                                       // 0x0198(0x000C) MISSED OFFSET
	TArray<struct FTriggeredCustomDamageEvent>         ClientEvents;                                             // 0x01A4(0x000C) (Net, ZeroConstructor)
	unsigned char                                      UnknownData04[0x50];                                      // 0x01B0(0x0050) MISSED OFFSET
	TMap<struct FName, class UObject*>                 CacheUObjectMap;                                          // 0x0200(0x0050) (ZeroConstructor)
	unsigned char                                      UnknownData05[0x4];                                       // 0x023C(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.CustomDamageEventComponent");
		return pStaticClass;
	}


	void OnRep_ClientEvents();
};


// Class AI.CharacterCustomDamageEventComponent
// 0x0000 (0x0240 - 0x0240)
class UCharacterCustomDamageEventComponent : public UCustomDamageEventComponent
{
public:

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.CharacterCustomDamageEventComponent");
		return pStaticClass;
	}


	void OnTakeDamageEvent(float Damage, const struct FDamageEvent& DamageEvent, class AActor* Victim, class AActor* Causer);
};


// Class AI.MLAIControllerComponent
// 0x0178 (0x0238 - 0x00C0)
class UMLAIControllerComponent : public UActorComponent
{
public:
	class UClass*                                      AISoundCollectCompClass;                                  // 0x00C0(0x0004) (Edit, ZeroConstructor, IsPlainOldData)
	class UClass*                                      AIStateInfoCompClass;                                     // 0x00C4(0x0004) (Edit, ZeroConstructor, IsPlainOldData)
	class UAIActionExecutionComponent*                 AIActionExecutionComp;                                    // 0x00C8(0x0004) (Edit, BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData)
	class UAIStateInfoComponent*                       AIStateInfoComp;                                          // 0x00CC(0x0004) (Edit, BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData)
	class UAISoundCollectionComponent*                 AISoundCollectComp;                                       // 0x00D0(0x0004) (Edit, BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData)
	float                                              HearRadius;                                               // 0x00D4(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	TMap<TEnumAsByte<ESTEPoseState>, struct FCameraViewPitchLimitData> CameraViewPitchLimitDataMap;                              // 0x00D8(0x0050) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FVector                                     PrePos;                                                   // 0x0114(0x000C) (IsPlainOldData)
	float                                              PreTickTime;                                              // 0x0120(0x0004) (ZeroConstructor, IsPlainOldData)
	class AController*                                 OwnerController;                                          // 0x0124(0x0004) (ZeroConstructor, IsPlainOldData)
	class ANewFakePlayerAIController*                  MyAIController;                                           // 0x0128(0x0004) (ZeroConstructor, IsPlainOldData)
	class ASTExtraPlayerController*                    MyPlayerController;                                       // 0x012C(0x0004) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x14];                                      // 0x0130(0x0014) MISSED OFFSET
	float                                              FindNavLocationRadius;                                    // 0x0144(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                MaxNavLocationFindTimes;                                  // 0x0148(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               bUseLerpRotation;                                         // 0x014C(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x3];                                       // 0x014D(0x0003) MISSED OFFSET
	float                                              LerpRotationThreshold;                                    // 0x0150(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               IsForceTargetRotation;                                    // 0x0154(0x0001) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData02[0x3];                                       // 0x0155(0x0003) MISSED OFFSET
	float                                              FirstLerpRotationDeltaTime;                               // 0x0158(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              FreeCameraTurnVelocity;                                   // 0x015C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              TurnVelocity;                                             // 0x0160(0x0004) (Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	struct FAIShootingPoseOffsetInfo                   shootingPoseOffsetInfo;                                   // 0x0164(0x0054) (Edit)
	float                                              AutoOpenDoorRange;                                        // 0x01B8(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData03[0x8];                                       // 0x01BC(0x0008) MISSED OFFSET
	bool                                               IsModifyDamageLuaOverride;                                // 0x01C4(0x0001) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData04[0x3];                                       // 0x01C5(0x0003) MISSED OFFSET
	float                                              RatingDamageScaleLuaOverride;                             // 0x01C8(0x0004) (ZeroConstructor, IsPlainOldData)
	bool                                               bShouldSendVehicleInfo;                                   // 0x01CC(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData05[0x1B];                                      // 0x01CD(0x001B) MISSED OFFSET
	bool                                               IsChangeStatePC;                                          // 0x01E8(0x0001) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData06[0x4F];                                      // 0x01E9(0x004F) MISSED OFFSET

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.MLAIControllerComponent");
		return pStaticClass;
	}


	void UnBindDelegates(bool IsEndPlay);
	void SetLuaAIParamConfigString(const struct FString& InAIParamConfigString);
	void SetIsMLAI(bool InIsMLAI);
	void SetCurShootingPose(EAIShootingPose InCurAIShootingPose);
	void SetAILevel(uint32_t NewAILevel);
	bool IsValid();
	bool IsFreeCamera();
	struct FRotator GetViewRotation();
	struct FVector GetViewForwardVector();
	class ASTExtraBaseCharacter* GetOwnerBaseCharacter();
	class UBackpackComponent* GetBackpackComponent();
	class UAIStateInfoComponent* GetAIStateInfoComp();
	uint32_t GetAILevel();
	class UAIActionExecutionComponent* GetAIActionExecutionComp();
	void DoActionFreeCamera(bool IsEnter, float InPitch, float InYaw, float InRoll);
	bool CheckCameraViewPitchLimit(struct FRotator* InOutTargetRot);
	void BindDelegates();
};


// Class AI.MLAISubSystem
// 0x0488 (0x04A8 - 0x0020)
class UMLAISubSystem : public UWorldSubsystem
{
public:
	struct FScriptMulticastDelegate                    OnAIStateRequestEnd;                                      // 0x0020(0x000C) (ZeroConstructor, InstancedReference)
	TMap<uint32_t, struct FAIPlayerState>              CacheAIPlayerStates;                                      // 0x002C(0x0050) (ZeroConstructor)
	TMap<uint32_t, struct FAIPlayerInteractInfo>       CachePlayerDamageInfo;                                    // 0x0068(0x0050) (ZeroConstructor)
	TMap<uint32_t, struct FVehicleDamageInfoContainer> CacheVehicleDamageInfo;                                   // 0x00A4(0x0050) (ZeroConstructor)
	int                                                MaxCacheDamageInfoNum;                                    // 0x00E0(0x0004) (ZeroConstructor, IsPlainOldData)
	TMap<uint32_t, struct FAIPlayerWeapon>             CacheAIPlayerWeapons;                                     // 0x00E4(0x0050) (ZeroConstructor)
	TMap<uint32_t, struct FAIPlayerEquipment>          CacheAIPlayerEquipments;                                  // 0x0120(0x0050) (ZeroConstructor)
	TArray<class UAIStateInfoComponent*>               AIStateInfoComps;                                         // 0x015C(0x000C) (ExportObject, ZeroConstructor)
	TArray<struct FBulletHoleRecordInfo>               CacheBulletHoles;                                         // 0x0168(0x000C) (ZeroConstructor)
	TArray<struct FSpecialZoneState>                   CacheSpecialZones;                                        // 0x0174(0x000C) (ZeroConstructor)
	TMap<uint32_t, struct FDiffAIPlayerState>          CacheDiffAIPlayerStates;                                  // 0x0180(0x0050) (ZeroConstructor)
	TMap<uint32_t, struct FDiffAIPlayerWeapon>         CacheDiffAIPlayerWeapons;                                 // 0x01BC(0x0050) (ZeroConstructor)
	TMap<uint32_t, struct FDiffAIPlayerEquipment>      CacheDiffAIPlayerEquipments;                              // 0x01F8(0x0050) (ZeroConstructor)
	TMap<uint32_t, bool>                               CacheDiffAIPlayerStatesRet;                               // 0x0234(0x0050) (ZeroConstructor)
	TMap<uint32_t, bool>                               CacheDiffAIPlayerWeaponsRet;                              // 0x0270(0x0050) (ZeroConstructor)
	TMap<uint32_t, bool>                               CacheDiffAIPlayerEquipmentsRet;                           // 0x02AC(0x0050) (ZeroConstructor)
	TMap<uint32_t, bool>                               DeadTeammatePlayerStateSendIDs;                           // 0x02E8(0x0050) (ZeroConstructor)
	TMap<uint32_t, struct FAIStateInfo>                CacheTeammatePlayerStateInfos;                            // 0x0324(0x0050) (ZeroConstructor)
	TMap<uint32_t, uint32_t>                           CacheDiffTeammatePlayerStateKeys;                         // 0x0360(0x0050) (ZeroConstructor)
	TMap<uint32_t, bool>                               TeammatePlayerDiffChecks;                                 // 0x039C(0x0050) (ZeroConstructor)
	TArray<struct FString>                             TeammateStateWhiteList;                                   // 0x03D8(0x000C) (ZeroConstructor)
	unsigned char                                      UnknownData00[0x3C];                                      // 0x03E4(0x003C) MISSED OFFSET
	TMap<uint32_t, struct FAIStateInfo>                CacheAllPlayerInfo;                                       // 0x0420(0x0050) (ZeroConstructor)
	unsigned char                                      UnknownData01[0xC];                                       // 0x045C(0x000C) MISSED OFFSET
	TMap<class AActor*, class ASpecialZoneActor*>      CacheSpecialZoneParents;                                  // 0x0468(0x0050) (ZeroConstructor)
	unsigned char                                      UnknownData02[0x4];                                       // 0x04A4(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.MLAISubSystem");
		return pStaticClass;
	}


	void UpdateSpecialZoneInfo(struct FSpecialZoneState* NewZoneInfo);
	void StartRequestCache();
	void SetSpecialZoneCustomState(class AActor* InParent, int InCustomState);
	void RemoveSpecialZoneInfo(uint32_t ZoneID, uint32_t Type);
	void OnVehicleDamageInfo(class AController* InstigatorController, class AController* VictimController, int DamageTypeId, float Damage, bool bIsFatalHealthCost, class AActor* DamageCauser, class AActor* VictimVehicle);
	void OnPlayerDamageInfo(class ASTExtraPlayerState* InstigatorPlayerState, class ASTExtraPlayerState* VictimPlayerState, float Damage, const struct FDamageEvent& DamageEvent, float DamageBeforeCalArmor, bool bIsFatalHealthCost, class AActor* DamageCauser);
	void OnItemStateChanged(const struct FVector& Location);
	bool IsAIBotGame();
	TArray<class ASTExtraBaseCharacter*> GetValidTeammatePlayers(class UAIStateInfoComponent* AIStateInfoComp);
	struct FAIStateInfo GetTeammatePlayerStateInfo(class UAIStateInfoComponent* InAIStateInfoComp, class ASTExtraBaseCharacter* InCharacter);
	float GetLossTime(class ASTExtraPlayerController* PlayerController);
	struct FDiffAIStateInfo GetDiffTeammatePlayerStateInfo(class UAIStateInfoComponent* InAIStateInfoComp, class ASTExtraBaseCharacter* InCharacter);
	void EndRequestCache();
	void ChangeMLAIInfo(class AFakePlayerAIController* AIController, const struct FString& Name, uint64_t DisplayUID, struct FPlayerOBInfo* OBInfo);
	void AddAIAttributeConfig(uint32_t InID, const struct FString& InKey);
};


// Class AI.MLAITrainingComponent
// 0x0018 (0x00D8 - 0x00C0)
class UMLAITrainingComponent : public UActorComponent
{
public:
	class APlayerState*                                PauseGamePlayerState;                                     // 0x00C0(0x0004) (ZeroConstructor, IsPlainOldData)
	bool                                               bIsPausing;                                               // 0x00C4(0x0001) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x13];                                      // 0x00C5(0x0013) MISSED OFFSET

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.MLAITrainingComponent");
		return pStaticClass;
	}


	void StopRunnable();
	void SetPauseGamePlayerState(class APlayerState* InPlayerState);
	bool SetPause(bool bInPause, float InPauseTime);
	void SendAIStateRequest(TArray<unsigned char> Packet);
	bool IsRequestAIState();
	void InitRunnable(float InStartCollectingInterval, float InSendInterval, float InTimeOutInterval);
	void EndRequestAIState();
};


// Class AI.SpecialZoneShapeComponent
// 0x0010 (0x0620 - 0x0610)
class USpecialZoneShapeComponent : public UPrimitiveComponent
{
public:
	float                                              SphereRadius;                                             // 0x0610(0x0004) (BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0xC];                                       // 0x0614(0x000C) MISSED OFFSET

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.SpecialZoneShapeComponent");
		return pStaticClass;
	}

};


// Class AI.SpecialZoneActor
// 0x0018 (0x0320 - 0x0308)
class ASpecialZoneActor : public AActor
{
public:
	int                                                ZoneID;                                                   // 0x0308(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              Radius;                                                   // 0x030C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                Type;                                                     // 0x0310(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                CustomState;                                              // 0x0314(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	class USpecialZoneShapeComponent*                  SpecialZoneShapeComponent;                                // 0x0318(0x0004) (Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData)
	class AActor*                                      CacheParentActor;                                         // 0x031C(0x0004) (ZeroConstructor, IsPlainOldData)

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.SpecialZoneActor");
		return pStaticClass;
	}


	void UpdateCustomState(int InCustomState);
	struct FSpecialZoneState GetSpecialZoneState();
};


// Class AI.STStrategyLocation_Range
// 0x0038 (0x0100 - 0x00C8)
class USTStrategyLocation_Range : public USTStrategyLocation
{
public:
	float                                              Range;                                                    // 0x00C8(0x0004) (Edit, ZeroConstructor, IsPlainOldData)
	int                                                MaxTryTimes;                                              // 0x00CC(0x0004) (Edit, ZeroConstructor, IsPlainOldData)
	unsigned char                                      bCheckPlayerSight : 1;                                    // 0x00D0(0x0001) (Edit)
	unsigned char                                      UnknownData00[0x3];                                       // 0x00D1(0x0003) MISSED OFFSET
	float                                              PlayerViewDistance;                                       // 0x00D4(0x0004) (Edit, ZeroConstructor, IsPlainOldData)
	TEnumAsByte<ECollisionChannel>                     CollisionChannel;                                         // 0x00D8(0x0001) (Edit, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x3];                                       // 0x00D9(0x0003) MISSED OFFSET
	float                                              MaxLocationTraceHeightZ;                                  // 0x00DC(0x0004) (Edit, ZeroConstructor, IsPlainOldData)
	TArray<struct FSpawnArea>                          CustomAreas;                                              // 0x00E0(0x000C) (Edit, ZeroConstructor)
	unsigned char                                      UnknownData02[0x14];                                      // 0x00EC(0x0014) MISSED OFFSET

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.STStrategyLocation_Range");
		return pStaticClass;
	}


	void ModifyBaseLocation(const struct FVector& InLocation);
	bool GetSpawnLocation(class AActor* Requester, int ReferenceCount, TArray<struct FSpawnSpotInfo>* OutArr);
	void AddSpawnArea(const struct FSpawnArea& NewArea, bool ForceAdd);
	void ActivateStrategy(class ASTSpawnerBase* Owner);
};


// Class AI.STStrategySpecies_Candidate
// 0x0000 (0x00D0 - 0x00D0)
class USTStrategySpecies_Candidate : public USTStrategySpecies
{
public:

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.STStrategySpecies_Candidate");
		return pStaticClass;
	}


	TArray<struct FUnitConfig> Supply(int ReferencedCount, TArray<struct FSpawnSpotInfo> SpotSpecies);
	void ActivateStrategy(class ASTSpawnerBase* Owner);
};


// Class AI.STStrategySpecies_Lua
// 0x0000 (0x00D0 - 0x00D0)
class USTStrategySpecies_Lua : public USTStrategySpecies
{
public:

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.STStrategySpecies_Lua");
		return pStaticClass;
	}


	TArray<struct FUnitConfig> Supply(int ReferencedCount, TArray<struct FSpawnSpotInfo> SpotSpecies);
	void LuaSupply(int ReferencedCount);
};


// Class AI.STStrategyTiming_Event
// 0x0018 (0x00C8 - 0x00B0)
class USTStrategyTiming_Event : public USTStrategyTiming
{
public:
	struct FString                                     EventId;                                                  // 0x00B0(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     EventName;                                                // 0x00BC(0x000C) (Edit, BlueprintVisible, ZeroConstructor)

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.STStrategyTiming_Event");
		return pStaticClass;
	}


	void TickStrategy(float DeltaTime);
	void OnSpawnEventBroadcast();
	void ActivateStrategy(class ASTSpawnerBase* Owner);
};


// Class AI.VehicleAIUserComponent
// 0x0000 (0x0198 - 0x0198)
class UVehicleAIUserComponent : public UVehicleUserComponentBase
{
public:

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.VehicleAIUserComponent");
		return pStaticClass;
	}


	void ServerVehicleLeanOut(bool bLeanOut);
	void ServerExitVehicle();
	void ServerEnterVehicle(class ASTExtraVehicleBase* InVehicle, unsigned char SeatType);
	void ServerChangeVehicleSeat(int InSeatIndex);
	void MulticastExitVehicle();
	void MulticastEnterVehicle(class ASTExtraVehicleBase* InVehicle, class ASTExtraPlayerCharacter* Pawn, bool bSuccess, unsigned char SeatType, int SeatIndex);
	void MulticastChangeVehicleSeat(int InSeatIndex);
};


// Class AI.VehicleCustomDamageEventComponent
// 0x0000 (0x0240 - 0x0240)
class UVehicleCustomDamageEventComponent : public UCustomDamageEventComponent
{
public:

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class AI.VehicleCustomDamageEventComponent");
		return pStaticClass;
	}


	void OnVehicleHPFuelChanged(float HP, float Fuel);
};


}

