#pragma once

// PUBG MOBILE 2.7.0 SDK generated by Huy#3877 

namespace SDK
{
//---------------------------------------------------------------------------
//Classes
//---------------------------------------------------------------------------

// BlueprintGeneratedClass PickUp_BP_Pants_06_B.PickUp_BP_Pants_06_B_C
// 0x0004 (0x06A4 - 0x06A0)
class APickUp_BP_Pants_06_B_C : public APickUpWrapperActor
{
public:
	class UStaticMeshComponent*                        Bag_03_icon;                                              // 0x06A0(0x0004) (BlueprintVisible, ZeroConstructor, IsPlainOldData)

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("BlueprintGeneratedClass PickUp_BP_Pants_06_B.PickUp_BP_Pants_06_B_C");
		return pStaticClass;
	}


	void UserConstructionScript();
};


}

