#pragma once

// PUBG MOBILE 2.5.0 SDK generated by Huy#3877 

#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function BP_Ammo_556mm_PickUp.BP_Ammo_556mm_Pickup_C.UserConstructionScript
struct ABP_Ammo_556mm_Pickup_C_UserConstructionScript_Params
{
};

}

