#pragma once

// PUBG MOBILE 2.5.0 SDK generated by Huy#3877 

#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function BP_WEP_Machete_10001.BP_WEP_Machete_10000_C.GetWeaponAttachToBackRelativeTransformByBagLevel_Lobby
struct ABP_WEP_Machete_10000_C_GetWeaponAttachToBackRelativeTransformByBagLevel_Lobby_Params
{
	int*                                               Level;                                                    // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
	int*                                               SideType;                                                 // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
	struct FTransform                                  ReturnValue;                                              // (Parm, OutParm, ReturnParm, IsPlainOldData)
};

// Function BP_WEP_Machete_10001.BP_WEP_Machete_10000_C.UserConstructionScript
struct ABP_WEP_Machete_10000_C_UserConstructionScript_Params
{
};

}

