#pragma once

// PUBG MOBILE 2.5.0 SDK generated by Huy#3877 

namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_DefaultItem_type.BP_STRUCT_DefaultItem_type
// 0x000C
struct FBP_STRUCT_DefaultItem_type
{
	int                                                id_0_4B6B0DC00A19AC576542439B088E7314;                    // 0x0000(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                type_1_1EAF2B00228F784E184E71BE0E7268E5;                  // 0x0004(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                subType_2_2D71558009ADD2D853D5382D043F6745;               // 0x0008(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
};

}

