#pragma once

// PUBG MOBILE 2.5.0 SDK generated by Huy#3877 

#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function LobbyMallAttachPoint_Vehicle.LobbyMallAttachPoint_Vehicle_C.NewFunction_1
struct ULobbyMallAttachPoint_Vehicle_C_NewFunction_1_Params
{
};

}

