#pragma once

// PUBG MOBILE 2.5.0 SDK generated by Huy#3877 

namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_WeaponPhysicsAsset_type.BP_STRUCT_WeaponPhysicsAsset_type
// 0x0010
struct FBP_STRUCT_WeaponPhysicsAsset_type
{
	struct FString                                     physics_asset_0_69E2394033CBBC235121B81B0E14C0C4;         // 0x0000(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                weapon_id_1_7F95664030BA5D031B0BF5E204A4AB84;             // 0x000C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
};

}

