#pragma once

// PUBG MOBILE 2.4.0 SDK generated by Huy#3877 

namespace SDK
{
//---------------------------------------------------------------------------
//Classes
//---------------------------------------------------------------------------

// BlueprintGeneratedClass VehicleAvatarHandle_BP_VH_UAZ01.VehicleAvatarHandle_BP_VH_UAZ01_C
// 0x0000 (0x0418 - 0x0418)
class UVehicleAvatarHandle_BP_VH_UAZ01_C : public UVehicleAvatarHandleBase_BP_C
{
public:

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("BlueprintGeneratedClass VehicleAvatarHandle_BP_VH_UAZ01.VehicleAvatarHandle_BP_VH_UAZ01_C");
		return pStaticClass;
	}

};


}

