#pragma once

// PUBG MOBILE 2.4.0 SDK generated by Huy#3877 

namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_CycleMemoryTaskCfg_type.BP_STRUCT_CycleMemoryTaskCfg_type
// 0x0028
struct FBP_STRUCT_CycleMemoryTaskCfg_type
{
	struct FString                                     TaskDesc_0_61BC4D004EAB49B010CBD0200B859673;              // 0x0000(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                TaskID_1_5647508030643F2A4E7C73130AEB85E4;                // 0x000C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     TaskTitle_2_5C0A0DC06B28E7990C34E8AA09AAA595;             // 0x0010(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     JumpID_3_151592C01760E3950435F9EA0C595EE4;                // 0x001C(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
};

}

