#pragma once

// PUBG MOBILE 2.4.0 SDK generated by Huy#3877 

#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function MinitvAvatarComponent_BP.MinitvAvatarComponent_BP_C.MakeAvatarTableData
struct UMinitvAvatarComponent_BP_C_MakeAvatarTableData_Params
{
	struct FItemDefineID                               InItemID;                                                 // (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FAvatarTableData                            ReturnValue;                                              // (Parm, OutParm, ReturnParm)
};

// Function MinitvAvatarComponent_BP.MinitvAvatarComponent_BP_C.RayEquipItemById
struct UMinitvAvatarComponent_BP_C_RayEquipItemById_Params
{
	int                                                ID;                                                       // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

